//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A card payment source */
public class PaymentRequestCardSource: Codable {

    public init() {
    }


    public required init(from decoder: Decoder) throws {
    }

    public func encode(to encoder: Encoder) throws {
    }

    public func isEqual(to object: Any?) -> Bool {
      guard object is PaymentRequestCardSource else { return false }
      return true
    }

    public static func == (lhs: PaymentRequestCardSource, rhs: PaymentRequestCardSource) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
