//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A token payment source */
public class PaymentRequestTokenSource: Codable {

    public init() {
    }


    public required init(from decoder: Decoder) throws {
    }

    public func encode(to encoder: Encoder) throws {
    }

    public func isEqual(to object: Any?) -> Bool {
      guard object is PaymentRequestTokenSource else { return false }
      return true
    }

    public static func == (lhs: PaymentRequestTokenSource, rhs: PaymentRequestTokenSource) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
