//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

/** The response media type */
public enum MediaType: String, Codable {
    case applicationjson = "application/json"

    public static let cases: [MediaType] = [
      .applicationjson,
    ]
}
